# Generated by Django 4.1.7 on 2023-02-26 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=155, null=True)),
                ("phone", models.CharField(blank=True, max_length=155, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="media/profile"),
                ),
                ("email", models.CharField(blank=True, max_length=155, null=True)),
                ("password", models.TextField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=155, null=True)),
                ("date_added", models.DateTimeField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
                "db_table": "account_profile",
                "ordering": ("date_added",),
            },
        ),
    ]
